### ISSUE TITLE
Ошибка версии .NET Framework в readme.md

### ISSUE THREAD

**Issue by MahBoiDeveloper** [YoVVassup/MOVision_Builder#3]
Вообще-то клиент требует наличия установленного .NET Framework 4.8, а не 4.0, как это указано [здесь](https://github.com/YoVVassup/MOVision_Builder?tab=readme-ov-file#ограничение).

Надо заменить текст и ссылку.

**Comment by YoVVassup** [comment]
Данное замечание некорректно, т.к. оно относится к моду (клиенту мода), а не "сборщику", причина того что я указал  .NET Framework 4.0. заключается в применении утилиты [CSFTool](https://github.com/Starkku/CSFTool), требующей эту версию для работы.

**Comment by MahBoiDeveloper** [comment]
> Данное замечание некорректно, т.к. оно относится к моду (клиенту мода), а не "сборщику", причина того что я указал .NET Framework 4.0. заключается в применении утилиты [CSFTool](https://github.com/Starkku/CSFTool), требующей эту версию для работы.

Чел, посмотри это.
![image](https://github.com/YoVVassup/MOVision_Builder/assets/61310813/e9e881bf-4969-4abb-9a3d-927721fb67bf)
Тут чёрным по белому написано про .NET Framework 4.8. А это, между прочим, библиотека, которую использует `CSFTool`.

**Comment by YoVVassup** [comment]
:D, любишь копаться, так раскапывай до конца https://github.com/Starkku/CSFTool/releases/tag/net40
