### ISSUE TITLE
Включить использование Git LFS

### ISSUE THREAD

**Issue by MahBoiDeveloper** [YoVVassup/MOVision_Builder#4]
Подробнее про [Git LFS](https://www.atlassian.com/ru/git/tutorials/git-lfs).

**Comment by YoVVassup** [comment]
Я уже пересмотрел много чего на эту тему, бинарные файлы не совсем то что может хорошо обрабатываться инструментами контроля версий, особенно когда они большого размера. По поводу ссылки выше смотри https://support.atlassian.com/bitbucket-cloud/docs/storage-policy-for-git-lfs-with-bitbucket/, что дает те же ограничения в 1Гб на LFS и 100Гб на весь репозиторий. Все работает одинаково для этих трех игроков Bitbucket \  Github \ Gitlab, и это уже проверено.
